In [ ]:
import torch

##### input data

In [2]:
input = 'Life is short, eat dessert first'

sentence = input.replace(',', '').split()

In [3]:
sentence

['Life', 'is', 'short', 'eat', 'dessert', 'first']

In [5]:
dc = {word:indx for indx, word in enumerate(sorted(sentence))}
dc

{'Life': 0, 'dessert': 1, 'eat': 2, 'first': 3, 'is': 4, 'short': 5}

In [6]:
indexed_sentence = torch.tensor([dc[word] for word in sentence])

indexed_sentence

tensor([0, 4, 5, 2, 1, 3])

##### embeddings

In [10]:
torch.manual_seed(123)

embed = torch.nn.Embedding(6, 16)
embed_sentence = embed(indexed_sentence).detach()

In [12]:
embed_sentence, embed_sentence.size()

(tensor([[ 0.3374, -0.1778, -0.3035, -0.5880,  0.3486,  0.6603, -0.2196, -0.3792,
           0.7671, -1.1925,  0.6984, -1.4097,  0.1794,  1.8951,  0.4954,  0.2692],
         [ 0.5146,  0.9938, -0.2587, -1.0826, -0.0444,  1.6236, -2.3229,  1.0878,
           0.6716,  0.6933, -0.9487, -0.0765, -0.1526,  0.1167,  0.4403, -1.4465],
         [ 0.2553, -0.5496,  1.0042,  0.8272, -0.3948,  0.4892, -0.2168, -1.7472,
          -1.6025, -1.0764,  0.9031, -0.7218, -0.5951, -0.7112,  0.6230, -1.3729],
         [-1.3250,  0.1784, -2.1338,  1.0524, -0.3885, -0.9343, -0.4991, -1.0867,
           0.8805,  1.5542,  0.6266, -0.1755,  0.0983, -0.0935,  0.2662, -0.5850],
         [-0.0770, -1.0205, -0.1690,  0.9178,  1.5810,  1.3010,  1.2753, -0.2010,
           0.4965, -1.5723,  0.9666, -1.1481, -1.1589,  0.3255, -0.6315, -2.8400],
         [ 0.8768,  1.6221, -1.4779,  1.1331, -1.2203,  1.3139,  1.0533,  0.1388,
           2.2473, -0.8036, -0.2808,  0.7697, -0.6596, -0.7979,  0.1838,  0.2293]]),
 torch.S

##### weight matrices

In [14]:
torch.manual_seed(123)


d = embed_sentence.shape[1]

d_q, d_k, d_v = 24, 24, 28

W_query = torch.nn.Parameter(torch.rand(d_q, d))
W_key = torch.nn.Parameter(torch.rand(d_k, d))
W_value = torch.nn.Parameter(torch.rand(d_v, d))

##### computing the **unnormalized** attention weights (for 2 word)

    query; keys; values for the second word

In [16]:
x_2 = embed_sentence[1]

query_2 = W_query.matmul(x_2)
key_2 = W_key.matmul(x_2)
value_2 = W_value.matmul(x_2)

    computing the remaining keys and values

In [17]:
keys = W_key.matmul(embed_sentence.T).T
values = W_value.matmul(embed_sentence.T).T

    computing the ω values for all input tokens

In [22]:
query_2.shape

torch.Size([24])

In [20]:
keys.shape, values.shape

(torch.Size([6, 24]), torch.Size([6, 28]))

In [18]:
omega_2 = query_2.matmul(keys.T)
omega_2

tensor([ 8.5808, -7.6597,  3.2558,  1.0395, 11.1466, -0.4800],
       grad_fn=<SqueezeBackward4>)